# Generated by Django 5.2.1 on 2025-06-03 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название датчика', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Описание датчика', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='Измеренная температура')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время измерения')),
                ('image', models.ImageField(blank=True, help_text='Изображение измерения', null=True, upload_to='sensor_measurements/')),
                ('sensor', models.ForeignKey(help_text='Связанный датчик', on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurement.sensor')),
            ],
        ),
    ]
